config/routes.rb
Spresso::Application.routes.draw do
    root :to => 'cafes#all'
    
  resources :cafes do
    resources :menus
  end

end

app/models/cafe.rb
class Cafe < ActiveRecord::Base
  attr_accessible :discount, :location, :name, :open_hour, :open_hour_etc, :open_hour_fri, :open_hour_wknd, :seat, :wifi
  has_many :menus
end

app/models/menu.rb
class Menu < ActiveRecord::Base
  belongs_to :cafe
  attr_accessible :name, :price
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/cafes_controller.rb
class CafesController < ApplicationController
    
    def all
        @cafes = Cafe.all
        render json: @cafes.map {|cafe| cafe.attributes.merge({:menus=>cafe.menus}) }
    end
    
  # GET /cafes
  # GET /cafes.json
  def index
    @cafes = Cafe.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @cafes }
    end
  end

  # GET /cafes/1
  # GET /cafes/1.json
  def show
    @cafe = Cafe.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @cafe }
    end
  end

  # GET /cafes/new
  # GET /cafes/new.json
  def new
    @cafe = Cafe.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @cafe }
    end
  end

  # GET /cafes/1/edit
  def edit
    @cafe = Cafe.find(params[:id])
  end

  # POST /cafes
  # POST /cafes.json
  def create
    @cafe = Cafe.new(params[:cafe])

    respond_to do |format|
      if @cafe.save
        format.html { redirect_to @cafe, notice: 'Cafe was successfully created.' }
        format.json { render json: @cafe, status: :created, location: @cafe }
      else
        format.html { render action: "new" }
        format.json { render json: @cafe.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /cafes/1
  # PUT /cafes/1.json
  def update
    @cafe = Cafe.find(params[:id])

    respond_to do |format|
      if @cafe.update_attributes(params[:cafe])
        format.html { redirect_to @cafe, notice: 'Cafe was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @cafe.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cafes/1
  # DELETE /cafes/1.json
  def destroy
    @cafe = Cafe.find(params[:id])
    @cafe.destroy

    respond_to do |format|
      format.html { redirect_to cafes_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/menus_controller.rb
class MenusController < ApplicationController
  # GET cafes/1/menus
  # GET cafes/1/menus.json
  def index
    @cafe = Cafe.find(params[:cafe_id])
    @menus = @cafe.menus

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @menus }
    end
  end

  # GET cafes/1/menus/1
  # GET cafes/1/menus/1.json
  def show
    @cafe = Cafe.find(params[:cafe_id])
    @menu = @cafe.menus.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @menu }
    end
  end

  # GET cafes/1/menus/new
  # GET cafes/1/menus/new.json
  def new
    @cafe = Cafe.find(params[:cafe_id])
    @menu = @cafe.menus.build

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @menu }
    end
  end

  # GET cafes/1/menus/1/edit
  def edit
    @cafe = Cafe.find(params[:cafe_id])
    @menu = @cafe.menus.find(params[:id])
  end

  # POST cafes/1/menus
  # POST cafes/1/menus.json
  def create
    @cafe = Cafe.find(params[:cafe_id])
    @menu = @cafe.menus.build(params[:menu])

    respond_to do |format|
      if @menu.save
        format.html { redirect_to([@menu.cafe, @menu], :notice => 'Menu was successfully created.') }
        format.json { render :json => @menu, :status => :created, :location => [@menu.cafe, @menu] }
      else
        format.html { render :action => "new" }
        format.json { render :json => @menu.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT cafes/1/menus/1
  # PUT cafes/1/menus/1.json
  def update
    @cafe = Cafe.find(params[:cafe_id])
    @menu = @cafe.menus.find(params[:id])

    respond_to do |format|
      if @menu.update_attributes(params[:menu])
        format.html { redirect_to([@menu.cafe, @menu], :notice => 'Menu was successfully updated.') }
        format.json { head :ok }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @menu.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE cafes/1/menus/1
  # DELETE cafes/1/menus/1.json
  def destroy
    @cafe = Cafe.find(params[:cafe_id])
    @menu = @cafe.menus.find(params[:id])
    @menu.destroy

    respond_to do |format|
      format.html { redirect_to cafe_menus_url(cafe) }
      format.json { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cafes_helper.rb
module CafesHelper
end

app/helpers/menus_helper.rb
module MenusHelper
end

app/views/cafes/_form.html.erb
<%= form_for(@cafe) do |f| %>
  <% if @cafe.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cafe.errors.count, "error") %> prohibited this cafe from being saved:</h2>

      <ul>
      <% @cafe.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :location %><br />
    <%= f.text_field :location %>
  </div>
  <div class="field">
    <%= f.label :seat %><br />
    <%= f.check_box :seat %>
  </div>
  <div class="field">
    <%= f.label :wifi %><br />
    <%= f.check_box :wifi %>
  </div>
  <div class="field">
    <%= f.label :discount %><br />
    <%= f.text_field :discount %>
  </div>
  <div class="field">
    <%= f.label :open_hour %><br />
    <%= f.text_field :open_hour %>
  </div>
  <div class="field">
    <%= f.label :open_hour_fri %><br />
    <%= f.text_field :open_hour_fri %>
  </div>
  <div class="field">
    <%= f.label :open_hour_wknd %><br />
    <%= f.text_field :open_hour_wknd %>
  </div>
  <div class="field">
    <%= f.label :open_hour_etc %><br />
    <%= f.text_field :open_hour_etc %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/cafes/edit.html.erb
<h1>Editing cafe</h1>

<%= render 'form' %>

<%= link_to 'Show', @cafe %> |
<%= link_to 'Back', cafes_path %>

app/views/cafes/index.html.erb
<h1>Listing cafes</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Location</th>
    <th>Seat</th>
    <th>Wifi</th>
    <th>Discount</th>
    <th>Open hour</th>
    <th>Open hour fri</th>
    <th>Open hour wknd</th>
    <th>Open hour etc</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @cafes.each do |cafe| %>
  <tr>
    <td><%= cafe.name %></td>
    <td><%= cafe.location %></td>
    <td><%= cafe.seat %></td>
    <td><%= cafe.wifi %></td>
    <td><%= cafe.discount %></td>
    <td><%= cafe.open_hour %></td>
    <td><%= cafe.open_hour_fri %></td>
    <td><%= cafe.open_hour_wknd %></td>
    <td><%= cafe.open_hour_etc %></td>
    <td><%= link_to 'Show', cafe %></td>
    <td><%= link_to 'Edit', edit_cafe_path(cafe) %></td>
    <td><%= link_to 'Destroy', cafe, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Cafe', new_cafe_path %>

app/views/cafes/new.html.erb
<h1>New cafe</h1>

<%= render 'form' %>

<%= link_to 'Back', cafes_path %>

app/views/cafes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @cafe.name %>
</p>

<p>
  <b>Location:</b>
  <%= @cafe.location %>
</p>

<p>
  <b>Seat:</b>
  <%= @cafe.seat %>
</p>

<p>
  <b>Wifi:</b>
  <%= @cafe.wifi %>
</p>

<p>
  <b>Discount:</b>
  <%= @cafe.discount %>
</p>

<p>
  <b>Open hour:</b>
  <%= @cafe.open_hour %>
</p>

<p>
  <b>Open hour fri:</b>
  <%= @cafe.open_hour_fri %>
</p>

<p>
  <b>Open hour wknd:</b>
  <%= @cafe.open_hour_wknd %>
</p>

<p>
  <b>Open hour etc:</b>
  <%= @cafe.open_hour_etc %>
</p>

<p>
  <b><%= link_to 'Menus', cafe_menus_path(@cafe) %></b>
</p>

<%= link_to 'Edit', edit_cafe_path(@cafe) %> |
<%= link_to 'Back', cafes_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Spresso</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/menus/_form.html.erb
<%= form_for([@menu.cafe, @menu]) do |f| %>
  <% if @menu.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@menu.errors.count, "error") %> prohibited this menu from being saved:</h2>

      <ul>
      <% @menu.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :price %><br />
    <%= f.text_field :price %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/menus/edit.html.erb
<h1>Editing menu</h1>

<%= render 'form' %>

<%= link_to 'Show', [@menu.cafe, @menu] %> |
<%= link_to 'Back', cafe_menus_path(@menu.cafe) %>

app/views/menus/index.html.erb
<h1>Listing menus</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Price</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @menus.each do |menu| %>
  <tr>
    <td><%= menu.name %></td>
    <td><%= menu.price %></td>
    <td><%= link_to 'Show', [menu.cafe, menu] %></td>
    <td><%= link_to 'Edit', edit_cafe_menu_path(menu.cafe, menu) %></td>
    <td><%= link_to 'Destroy', [menu.cafe, menu], :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Menu', new_cafe_menu_path(params[:cafe_id]) %>

app/views/menus/new.html.erb
<h1>New menu</h1>

<%= render 'form' %>

<%= link_to 'Back', cafe_menus_path(@menu.cafe) %>

app/views/menus/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @menu.name %>
</p>

<p>
  <b>Price:</b>
  <%= @menu.price %>
</p>


<%= link_to 'Edit', edit_cafe_menu_path(@menu.cafe, @menu) %> |
<%= link_to 'Back', cafe_menus_path(@menu.cafe) %>